(() => {
  'use strict';
  /* v1.0.1 compatibility safeguards. */
  const TOKEN_KEY='jasper_pokedex_github_token';let lastToken=null;
  const hasToken=()=>!!localStorage.getItem(TOKEN_KEY);
  const ensureDesktopTitle=()=>{const workspace=document.getElementById('desktopWorkspace');if(!workspace)return;let title=document.getElementById('desktopWorkspaceTitle');if(title){title.textContent=window.JASPER_POKEDEX?.gameConfig?.name||'Pokémon White 2';return;}const banner=document.getElementById('dexProgressBanner');title=document.createElement('h1');title.id='desktopWorkspaceTitle';title.textContent=window.JASPER_POKEDEX?.gameConfig?.name||'Pokémon White 2';title.setAttribute('aria-live','polite');workspace.insertBefore(title,banner||workspace.firstChild);};
  const setBulkAvailability=active=>{const toggle=document.getElementById('bulkModeToggle');if(!toggle)return;if(!active&&toggle.checked){toggle.checked=false;toggle.dispatchEvent(new Event('change',{bubbles:true}));}toggle.disabled=!active;toggle.setAttribute('aria-disabled',String(!active));const row=toggle.closest('.bulk-toggle-row');if(row)row.classList.toggle('bulk-disabled',!active);};
  const syncBulkAvailability=()=>{const active=hasToken();if(active===lastToken){setBulkAvailability(active);return;}lastToken=active;setBulkAvailability(active);};
  const install=()=>{ensureDesktopTitle();syncBulkAvailability();if(!document.getElementById('v01353BugFixStyles')){const style=document.createElement('style');style.id='v01353BugFixStyles';style.textContent=`.bulk-toggle-row input:disabled{cursor:not-allowed!important}.bulk-toggle-row.bulk-disabled{cursor:not-allowed!important;opacity:.6}@media(max-width:640px){html[data-theme="dark"] #mobileHeader #githubSyncMenu{background:#242831!important;color:#f5f7fa!important;border-color:#343a46!important;box-shadow:0 16px 36px rgba(0,0,0,.32)!important}html[data-theme="dark"] #mobileHeader #githubSyncMenu #githubSyncStatus{color:#c5cad3!important}html[data-theme="dark"] #mobileHeader #githubSyncMenu #githubLastSynced{color:#9aa3b2!important}html[data-theme="dark"] #mobileHeader #githubSyncMenu #githubTokenInput{background:#1c1f26!important;color:#f5f7fa!important;border-color:#454c59!important}html[data-theme="dark"] #mobileHeader #githubSyncMenu #githubTokenInput::placeholder{color:#7d8797!important}html[data-theme="dark"] #mobileHeader #githubSyncMenu #githubSyncControls button{background:#242831!important;color:#f5f7fa!important;border-color:#454c59!important}html[data-theme="dark"] #mobileHeader #githubSyncMenu #githubSyncControls button:hover{background:#203b63!important;border-color:#5b9cff!important}html[data-theme="dark"] #mobileHeader #githubSyncMenu #githubSyncNote{color:#9aa3b2!important}}`;document.head.appendChild(style);}};
  const boot=()=>{install();setTimeout(ensureDesktopTitle,0);setInterval(syncBulkAvailability,250);};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
