(() => {
  'use strict';

  /* Beta v0.11 compatibility layer.
   * This file owns only desktop presentation and Bulk Mode. It does NOT own
   * Pokémon rendering, counters, moniker text, sync, or form normalization. */
  const STATE_KEY='jasper_pokedex_state_White2';
  const isMobile=()=>matchMedia('(max-width:640px)').matches;
  let bulkMode=false,baseline=null,bulkCommitting=false,bulkInstalled=false,desktopInstalled=false;
  const getState=()=>{try{return JSON.parse(localStorage.getItem(STATE_KEY)||'{}')}catch{return{}}};
  const setNative=enabled=>{const native=window.__jasperSyncNativeSetItem;if(!native)return;if(enabled){if(!window.__jasperBulkWrappedSetItem)window.__jasperBulkWrappedSetItem=Storage.prototype.setItem;Storage.prototype.setItem=native;}else if(window.__jasperBulkWrappedSetItem)Storage.prototype.setItem=window.__jasperBulkWrappedSetItem;};
  const pill=(label,type)=>window.JASPER_SYNC_SET_PILL?.(label,type);
  const pending=()=>{if(!baseline)return[];const cur=getState();return[...new Set([...Object.keys(baseline),...Object.keys(cur)])].filter(id=>!!baseline[id]!==!!cur[id]);};
  const visuals=()=>{document.querySelectorAll('.bulk-pending').forEach(e=>e.classList.remove('bulk-pending'));if(!bulkMode||!baseline)return;pending().forEach(id=>document.querySelectorAll(`[data-id="${CSS.escape(id)}"]`).forEach(e=>e.classList.add('bulk-pending')));const n=pending().length,c=document.getElementById('bulkPendingCount'),b=document.getElementById('bulkCommitBtn');if(c)c.textContent=`${n} pending ${n===1?'change':'changes'}`;if(b)b.disabled=!n||bulkCommitting;if(bulkMode)pill('Bulk Mode','busy');};
  const setUI=()=>{const t=document.getElementById('bulkModeToggle'),a=document.getElementById('bulkActions');if(t)t.checked=bulkMode;if(a)a.hidden=!bulkMode;visuals();};
  const enter=()=>{if(bulkMode||bulkCommitting)return;baseline=JSON.parse(JSON.stringify(getState()));bulkMode=true;setNative(true);setUI();};
  const cancel=()=>{if(!bulkMode)return;const old=JSON.parse(JSON.stringify(baseline||{}));setNative(true);Storage.prototype.setItem.call(localStorage,STATE_KEY,JSON.stringify(old));localStorage.setItem('b2w2_living_dex_saved_state',JSON.stringify(old));bulkMode=false;baseline=null;setNative(false);document.querySelectorAll('[data-id]').forEach(e=>{const id=e.dataset.id;if(id)e.classList.toggle('completed',!!old[id]);});setUI();pill('Synced','ok');};
  const commit=()=>{const n=pending().length;if(!bulkMode||bulkCommitting||!n)return;bulkCommitting=true;setNative(false);const state=JSON.stringify(getState());localStorage.setItem(STATE_KEY,state);localStorage.setItem('b2w2_living_dex_saved_state',state);bulkMode=false;baseline=null;document.querySelectorAll('.bulk-pending').forEach(e=>e.classList.remove('bulk-pending'));pill('Syncing...','busy');setTimeout(()=>{bulkCommitting=false;},1500);};
  const installBulk=()=>{if(bulkInstalled)return;const menu=document.getElementById('githubSyncMenu');if(!menu)return;bulkInstalled=true;const section=document.createElement('section');section.id='bulkModeSection';section.innerHTML=`<div class="bulk-separator"></div><label class="bulk-toggle-row"><span><strong>Bulk Mode</strong><small>Hold entry changes until you manually commit them.</small></span><input id="bulkModeToggle" type="checkbox" aria-label="Enable Bulk Mode"></label><div id="bulkActions" hidden><div id="bulkPendingCount">0 pending changes</div><div class="bulk-action-buttons"><button id="bulkCommitBtn" type="button" disabled>Commit Bulk Entries</button><button id="bulkCancelBtn" type="button">Cancel</button></div></div>`;menu.appendChild(section);document.getElementById('bulkModeToggle').onchange=e=>e.target.checked?enter():cancel();document.getElementById('bulkCommitBtn').onclick=e=>{e.stopPropagation();commit()};document.getElementById('bulkCancelBtn').onclick=e=>{e.stopPropagation();document.getElementById('bulkModeToggle').checked=false;cancel()};document.addEventListener('click',e=>{if(!bulkMode||bulkCommitting)return;if(e.target.closest('#boxContainer .cell:not(.empty),#listContainer .list-row,.search-result-item'))setTimeout(visuals,0)},true);setUI();};
  const desktop=()=>{if(isMobile()||desktopInstalled)return;desktopInstalled=true;let side=document.getElementById('desktopSidebar');if(!side){side=document.createElement('aside');side.id='desktopSidebar';side.innerHTML=`<div class="desktop-sidebar-brand"><div class="brand-title">Jasper's Pokédex</div><div class="beta"></div></div><div class="desktop-sidebar-separator"></div><div class="desktop-sidebar-subheader">Titles</div><div class="desktop-title-tabs"></div>`;document.body.appendChild(side);}const tabs=document.querySelector('.tabs-container');if(tabs)side.querySelector('.desktop-title-tabs').appendChild(tabs);let work=document.getElementById('desktopWorkspace');if(!work){work=document.createElement('main');work.id='desktopWorkspace';document.body.appendChild(work);}let top=document.getElementById('desktopWorkspaceTop');if(!top){top=document.createElement('div');top.id='desktopWorkspaceTop';work.appendChild(top);}let title=document.getElementById('desktopWorkspaceTitle');if(!title){title=document.createElement('h1');title.id='desktopWorkspaceTitle';top.appendChild(title);}title.textContent='Pokémon White 2';const sync=document.getElementById('githubSyncWrap');if(sync)top.appendChild(sync);const banner=document.getElementById('dexProgressBanner');if(banner)work.appendChild(banner);let table=document.getElementById('desktopTableContainer');if(!table){table=document.createElement('section');table.id='desktopTableContainer';work.appendChild(table);}const controls=document.querySelector('.controls-container'),main=document.querySelector('.main-content');if(controls&&!table.contains(controls))table.appendChild(controls);if(main&&!table.contains(main))table.appendChild(main);};
  const styles=()=>{if(document.getElementById('v011BaseStyles'))return;const s=document.createElement('style');s.id='v011BaseStyles';s.textContent=`.box-title{display:flex!important;align-items:center;justify-content:space-between;gap:12px}.box-completion-counter{margin-left:auto;flex-shrink:0;font-size:.78rem;font-weight:700;color:#64748b;white-space:nowrap}.bulk-separator{border-top:1px solid #e2e8f0;margin:12px 0}.bulk-toggle-row{display:flex;align-items:center;justify-content:space-between;gap:12px;cursor:pointer}.bulk-toggle-row span{display:flex;flex-direction:column;gap:3px}.bulk-toggle-row strong{color:#1e293b;font-size:.82rem}.bulk-toggle-row small{color:#64748b;font-size:.72rem}.bulk-action-buttons{display:flex;gap:8px;margin-top:8px}.bulk-action-buttons button{flex:1;padding:9px 10px;border:1px solid #cbd5e1;border-radius:7px;background:#f8fafc;font-weight:700;cursor:pointer}.bulk-pending{background:#eff6ff!important;border-color:#60a5fa!important;opacity:1!important}.bulk-pending .checkbox{background:#3b82f6!important;border-color:#3b82f6!important}@media(min-width:641px){html,body{height:100%;overflow:hidden!important}body{padding:0!important;margin:0!important;background:#f1f5f9}#desktopSidebar{position:fixed;left:0;top:0;bottom:0;width:272px;background:#fff;border-right:1px solid #cbd5e1;padding:28px 20px;z-index:8000;box-shadow:3px 0 14px rgba(15,23,42,.05)}.desktop-sidebar-brand .brand-title{font-size:1.45rem;font-weight:700;color:#0f172a}.desktop-sidebar-brand .beta{margin-top:4px;color:#475569;font-size:.9rem;font-weight:600}.desktop-sidebar-separator{height:2px;background:#e2e8f0;margin:24px 0}.desktop-sidebar-subheader{font-size:.82rem;font-weight:700;color:#64748b;margin-bottom:10px}.desktop-title-tabs{display:flex;flex-direction:column;gap:8px}.desktop-title-tabs .tab-btn{width:100%;text-align:left}.desktop-title-tabs .tab-btn.disabled{opacity:.55}#desktopWorkspace{position:fixed;left:272px;right:0;top:0;bottom:0;display:flex;flex-direction:column;min-width:0;padding:24px 32px 28px;overflow:hidden}#desktopWorkspaceTop{display:flex;align-items:center;justify-content:space-between;gap:16px;flex:0 0 auto;margin-bottom:16px;z-index:11000}.desktopWorkspaceTitle{margin:0}#desktopWorkspaceTitle{margin:0;font-size:1.45rem;color:#0f172a}.#desktopWorkspace #dexProgressBanner{flex:0 0 auto}.#desktopTableContainer{display:flex;flex-direction:column;min-height:0;flex:1;background:#fff;border:1px solid #cbd5e1;border-radius:14px;padding:16px;overflow:hidden}#desktopTableContainer .controls-container{max-width:none!important;width:100%;margin:0 0 14px!important;flex:0 0 auto}#desktopTableContainer .main-content{display:block!important;max-width:none!important;width:100%;margin:0;flex:1;min-height:0;overflow-y:auto;overflow-x:hidden;padding:0 4px 28px 0}#desktopWorkspace .grid-wrapper{overflow-x:auto}}@media(max-width:640px){.desktopSidebar{display:none}.desktop-title-tabs{display:none}}`;document.head.appendChild(s);};
  const boot=()=>{styles();desktop();installBulk();};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
