(() => {
  'use strict';

  const API_ROOT='https://pokeapi.co/api/v2';
  const CACHE_KEY='jasper_pokeapi_cache_v2';
  const cache=new Map(),pending=new Map();
  const FAMILY={
    'pokemon-white-2':['black','white','black-2','white-2'],'pokemon-black-2':['black','white','black-2','white-2'],'pokemon-white':['black','white','black-2','white-2'],'pokemon-black':['black','white','black-2','white-2'],
    'pokemon-alpha-sapphire':['x','y','omega-ruby','alpha-sapphire'],'pokemon-omega-ruby':['x','y','omega-ruby','alpha-sapphire'],'pokemon-x':['x','y','omega-ruby','alpha-sapphire'],'pokemon-y':['x','y','omega-ruby','alpha-sapphire'],
    'pokemon-sun':['sun','moon','ultra-sun','ultra-moon'],'pokemon-moon':['sun','moon','ultra-sun','ultra-moon'],'pokemon-ultra-sun':['sun','moon','ultra-sun','ultra-moon'],'pokemon-ultra-moon':['sun','moon','ultra-sun','ultra-moon']
  };
  const LABEL={black:'Black',white:'White','black-2':'Black 2','white-2':'White 2',x:'X',y:'Y','omega-ruby':'Omega Ruby','alpha-sapphire':'Alpha Sapphire',sun:'Sun',moon:'Moon','ultra-sun':'Ultra Sun','ultra-moon':'Ultra Moon'};
  const STARTERS={black:['snivy','tepig','oshawott'],white:['snivy','tepig','oshawott'],'black-2':['snivy','tepig','oshawott'],'white-2':['snivy','tepig','oshawott'],x:['chespin','fennekin','froakie'],y:['chespin','fennekin','froakie'],'omega-ruby':['treecko','torchic','mudkip'],'alpha-sapphire':['treecko','torchic','mudkip'],sun:['rowlet','litten','popplio'],moon:['rowlet','litten','popplio'],'ultra-sun':['rowlet','litten','popplio'],'ultra-moon':['rowlet','litten','popplio']};
  const GEN={5:'generation-v',6:'generation-vi',7:'generation-vii'};
  const CYCLE={5:257,6:257,7:256};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const title=v=>String(v||'').split('-').map(x=>x?x[0].toUpperCase()+x.slice(1):x).join(' ');
  const get=async path=>{const url=path.startsWith('http')?path:`${API_ROOT}/${path.replace(/^\//,'')}`;if(cache.has(url))return cache.get(url);if(pending.has(url))return pending.get(url);let p=fetch(url,{headers:{Accept:'application/json'}}).then(async r=>{if(!r.ok)throw Error(`PokéAPI request failed (${r.status})`);const d=await r.json();cache.set(url,d);try{const o={};for(const[k,v]of cache)o[k]=v;localStorage.setItem(CACHE_KEY,JSON.stringify(o))}catch(_){}pending.delete(url);return d}).catch(e=>{pending.delete(url);throw e});pending.set(url,p);return p};
  const loadStored=()=>{try{const o=JSON.parse(localStorage.getItem(CACHE_KEY)||'{}');Object.entries(o).forEach(([k,v])=>cache.set(k,v))}catch(_){}};
  loadStored();
  const game=()=>window.JASPER_ACTIVE_GAME||'pokemon-white-2';
  const generation=g=>/pokemon-(white|black)(-2)?$/.test(g)?5:/pokemon-(alpha-sapphire|omega-ruby|x|y)$/.test(g)?6:/pokemon-(sun|moon|ultra-sun|ultra-moon)$/.test(g)?7:0;
  const versions=()=>FAMILY[game()]||[];
  const candidates=(name,form)=>{const n=String(name||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim(),f=String(form||'').toLowerCase().replace(/^\(|\)$/g,'').trim();const aliases={'diglett|alolan':'diglett-alola','dugtrio|alolan':'dugtrio-alola','geodude|alolan':'geodude-alola','graveler|alolan':'graveler-alola','golem|alolan':'golem-alola','meowth|alolan':'meowth-alola','persian|alolan':'persian-alola','rattata|alolan':'rattata-alola','raticate|alolan':'raticate-alola','raichu|alolan':'raichu-alola','sandshrew|alolan':'sandshrew-alola','sandslash|alolan':'sandslash-alola','vulpix|alolan':'vulpix-alola','ninetales|alolan':'ninetales-alola','marowak|alolan':'marowak-alola','exeggutor|alolan':'exeggutor-alola','grimer|alolan':'grimer-alola','muk|alolan':'muk-alola'};const key=`${n}|${f}`;const slug=x=>x.replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');return [...new Set([aliases[key],f&&f!=='normal'?slug(n)+'-'+slug(f):null,slug(n)].filter(Boolean))]};
  const fetchPokemon=async(card)=>{const name=card?.dataset?.name||'';const form=card?.dataset?.form||'';for(const c of candidates(name,form)){try{return await get(`pokemon/${c}`)}catch(_){}}throw Error(`PokéAPI could not identify ${name||'the selected Pokémon'}.`)};
  const species=async p=>get(p.species?.url||`pokemon-species/${p.species?.name||p.name}`);
  const englishName=async name=>{try{const s=await get(`pokemon-species/${name}`);return s.names?.find(x=>x.language?.name==='en')?.name||title(name)}catch(_){return title(name)}};
  const req=d=>{if(!d)return '';const a=[];if(d.min_level!=null)a.push(`Lvl ${d.min_level}`);if(d.item?.name)a.push(`use ${title(d.item.name)}`);if(d.trigger?.name==='trade')a.push(d.trade_species?.name?`trade for ${title(d.trade_species.name)}`:'trade');if(d.min_happiness!=null)a.push(`friendship ${d.min_happiness}`);if(d.min_beauty!=null)a.push(`beauty ${d.min_beauty}`);if(d.min_affection!=null)a.push(`affection ${d.min_affection}`);if(d.held_item?.name)a.push(`holding ${title(d.held_item.name)}`);if(d.known_move?.name)a.push(`knowing ${title(d.known_move.name)}`);if(d.known_move_type?.name)a.push(`knowing a ${title(d.known_move_type.name)}-type move`);if(d.location?.name)a.push(`at ${title(d.location.name)}`);if(d.time_of_day)a.push(`during ${d.time_of_day}`);if(d.gender===1)a.push('as female');if(d.gender===2)a.push('as male');if(d.near_special_rock)a.push('near a special rock');if(d.needs_overworld_rain)a.push('during rain');if(d.needs_multiplayer)a.push('with multiplayer');if(d.party_species?.name)a.push(`with ${title(d.party_species.name)} in party`);if(d.party_type?.name)a.push(`with a ${title(d.party_type.name)}-type Pokémon in party`);if(d.relative_physical_stats===1)a.push('with Attack greater than Defense');if(d.relative_physical_stats===0)a.push('with Attack equal to Defense');if(d.relative_physical_stats===-1)a.push('with Attack lower than Defense');if(d.used_move?.name)a.push(`using ${title(d.used_move.name)}`);if(d.min_move_count!=null)a.push(`${d.min_move_count} move uses`);if(d.min_steps!=null)a.push(`${d.min_steps} steps`);if(d.min_damage_taken!=null)a.push(`${d.min_damage_taken} damage taken`);if(d.turn_upside_down)a.push('turn the console upside down');return a.join(' and ')};
  const evolution=async(s)=>{if(!s.evolution_chain?.url)return 'No evolution chain data available.';const chain=await get(s.evolution_chain.url),edges=[];const walk=async node=>{const from=await englishName(node.species.name);for(const next of node.evolves_to||[]){const to=await englishName(next.species.name);const details=next.evolution_details||[];if(details.length)details.forEach(d=>edges.push(`${from} evolves to ${to} ${req(d)}.`));else edges.push(`${from} evolves to ${to}.`);await walk(next)}};await walk(chain.chain);return edges.length?edges.join(' '):`${await englishName(s.name)} does not evolve.`};
  const method=n=>({'walk':'Tall Grass','surf':'Surfing','old-rod':'Old Rod','good-rod':'Good Rod','super-rod':'Super Rod','rock-smash':'Rock Smash','headbutt':'Headbutt','dark-grass':'Dark Grass','walking':'Walking'}[n]||title(n||'Unknown'));
  const locations=async(p)=>{const vs=versions(),rows=[];let encounters=[];if(p.location_area_encounters)encounters=await get(p.location_area_encounters);const areaRows=await Promise.all((encounters||[]).map(async area=>{const loc=area.location_area?.name||'Unknown';const out=[];for(const d of area.version_details||[]){if(!vs.includes(d.version?.name))continue;for(const e of d.encounter_details||[])out.push({game:LABEL[d.version.name]||title(d.version.name),location:title(loc),method:method(e.method?.name),chance:e.chance??d.max_chance??null,min:e.min_level??null,max:e.max_level??null})}return out}));rows.push(...areaRows.flat());const sp=p.species?.name||p.name;vs.forEach(v=>{if((STARTERS[v]||[]).includes(sp))rows.push({game:LABEL[v],location:'Starter Pokémon',method:'Starter Pokémon',chance:null,min:null,max:null})});const seen=new Set();return rows.filter(r=>{const k=JSON.stringify(r);if(seen.has(k))return false;seen.add(k);return true})};
  const held=p=>{const vs=versions(),out=[];for(const h of p.held_items||[]){const d=(h.version_details||[]).filter(x=>vs.includes(x.version?.name));if(!d.length)continue;const rarity=Math.max(...d.map(x=>x.rarity||0));out.push(`${title(h.item?.name)}${rarity?` — ${rarity}%`:''}`)}return out};
  const typeData=async(p,s)=>{const g=generation(game()),past=(p.past_types||[]).find(x=>x.generation?.name===GEN[g]);return (past?.types?.length?past.types:p.types||[]).sort((a,b)=>a.slot-b.slot).map(x=>x.type.name)};
  const damage=async(types)=>{const g=generation(game()),gen=await get(`generation/${g}`),attackers=(gen.types||[]).map(x=>x.name),rels=await Promise.all(attackers.map(async a=>[a,await get(`type/${a}`)])),b={'2x':[],'1x':[],'0.5x':[],'0x':[]};for(const[a,data]of rels){let m=1;for(const def of types){const past=(data.past_damage_relations||[]).find(x=>x.generation?.name===GEN[g]);const r=past?.damage_relations||data.damage_relations;if(r.no_damage_from?.some(x=>x.name===def))m=0;else if(r.half_damage_from?.some(x=>x.name===def))m*=.5;else if(r.double_damage_from?.some(x=>x.name===def))m*=2}const k=m===0?'0x':m===.5?'0.5x':m===2?'2x':'1x';b[k].push(title(a))}return b};
  const row=(label,value)=>`<div class="jasper-api-row"><span class="jasper-api-label">${esc(label)}</span><span class="jasper-api-value">${esc(value)}</span></div>`;
  const list=(label,items)=>items.length?`<div class="jasper-api-list-label">${esc(label)}</div><ul>${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'';
  const render=(card,p,s,evo,loc,dmg)=>{const side=document.getElementById('desktopRightSidebar');if(!side)return;const types=typeDataSync(p,s),regional=card.dataset.num||card.querySelector('.dex-num')?.textContent?.trim()||'—',national=String(p.id).padStart(3,'0'),g=generation(game()),egg=s.hatch_counter==null?'—':`${CYCLE[g]?(CYCLE[g]*(s.hatch_counter+1)).toLocaleString():'—'} steps`;const heldRows=held(p),locationRows=loc.map(x=>`${x.game}: ${x.location} — ${x.method}${x.chance!=null?` — ${x.chance}%`:''}${x.min!=null?` — Lv. ${x.min}${x.max!==x.min?`–${x.max}`:''}`:''}`),drows=['2x','1x','0.5x','0x'].map(k=>row(k,dmg[k].join(', ')||'None')).join('');side.innerHTML=`<div class="jasper-api-pokedex"><p class="jasper-api-pokedex-title">${esc(p.name)}</p><p class="jasper-api-pokedex-subtitle">${esc(LABEL[game()]||title(game()))} · Generation ${g||'—'}</p><section class="jasper-api-card"><h2>Pokémon</h2>${row('Pokémon',p.name)}${row('Regional Dex Number','#'+regional)}${row('National Dex Number','#'+national)}${row('Type',types.map(title).join(' / ')||'—')}</section><section class="jasper-api-card"><h2>Evolutionary Chain</h2><p>${esc(evo)}</p></section><section class="jasper-api-card"><h2>Wild Locations</h2>${locationRows.length?`<ul>${locationRows.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p>Not available in the selected generation family.</p>'}</section><section class="jasper-api-card"><h2>Additional Information</h2>${row('Base Egg Steps',egg)}${row('Capture Rate',s.capture_rate==null?'—':String(s.capture_rate))}<div class="jasper-api-list-label">Damage Taken</div>${drows}${list('Wild Hold Items',heldRows)}</section></div>`};
  let lastTypes=[];const typeDataSync=()=>lastTypes;
  const loading=card=>{const side=document.getElementById('desktopRightSidebar');if(side)side.innerHTML=`<div class="jasper-api-pokedex"><p class="jasper-api-pokedex-title">Pokédex</p><p class="jasper-api-pokedex-subtitle">Loading Pokémon data…</p><section class="jasper-api-card"><h2>Pokémon</h2>${row('Selected',card?.dataset?.name||'Unknown')}</section></div>`};
  const error=e=>{const side=document.getElementById('desktopRightSidebar');if(side)side.innerHTML=`<div class="jasper-api-pokedex"><p class="jasper-api-pokedex-title">Pokédex</p><section class="jasper-api-card"><h2>Unable to load data</h2><p>${esc(e?.message||'PokéAPI request failed.')}</p></section></div>`;console.error('[Jasper PokéAPI]',e)};
  const open=async card=>{loading(card);try{const p=await fetchPokemon(card),s=await species(p);lastTypes=await typeData(p,s);const [evo,loc,dmg]=await Promise.all([evolution(s),locations(p),damage(lastTypes)]);render(card,p,s,evo,loc,dmg)}catch(e){error(e)}};
  window.JASPER_POKEDEX_UI={open};
})();
