(() => {
  'use strict';

  /* Beta v0.11.0.1
   * SINGLE OWNER for Pokémon data, progress state, Boxes, List, Search,
   * counters and view behavior. GitHub sync and desktop/Bulk presentation
   * remain separate owners. */

  const DEFAULT_GAME='White2', RAW_ROOT='https://raw.githubusercontent.com/lingjasper/Jasper-Pokedex/main/Pokedexes/', API_ROOT='https://api.github.com/repos/lingjasper/Jasper-Pokedex/contents/Pokedexes?ref=main';
  const BOX_SIZE=30, BOX_COLUMNS=6, BOX_ROWS=5, STATE_PREFIX='jasper_pokedex_state_', LEGACY_KEY='b2w2_living_dex_saved_state';
  let activeGame=DEFAULT_GAME, activePokemon=[], booted=false;

  const stateKey=game=>`${STATE_PREFIX}${game}`;
  const readState=game=>{try{const current=JSON.parse(localStorage.getItem(stateKey(game))||'null');if(current&&typeof current==='object')return current;if(game===DEFAULT_GAME){const legacy=JSON.parse(localStorage.getItem(LEGACY_KEY)||'null');if(legacy&&typeof legacy==='object')return legacy;}}catch(_){}return{}};
  const writeState=(game,state)=>{localStorage.setItem(stateKey(game),JSON.stringify(state));if(game===DEFAULT_GAME)localStorage.setItem(LEGACY_KEY,JSON.stringify(state));};
  const normalize=v=>String(v).toLocaleLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
  const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

  const parseSource=text=>{const out=[],counts=new Map();for(const line of text.split(/\r?\n/)){const m=line.match(/^\|\s*#?(\d+)\s*\|\s*(.*?)\s*\|\s*$/);if(!m)continue;const num=m[1].padStart(3,'0'),name=m[2].trim();if(!name||/^-+$/.test(name))continue;const fm=name.match(/^(.*?)\s*(\([^)]*\))$/),baseName=fm?fm[1].trim():name,form=fm?fm[2]:'';const n=counts.get(num)||0;counts.set(num,n+1);out.push({id:n?`${num}-${n}`:num,num,name,baseName,form});}return out;};
  const loadGame=async game=>{const r=await fetch(`${RAW_ROOT}${encodeURIComponent(game)}`,{cache:'no-store'});if(!r.ok)throw new Error(`Could not load Pokedexes/${game} (${r.status}).`);return parseSource(await r.text());};
  const discoverGames=async()=>{try{const r=await fetch(API_ROOT,{cache:'no-store'});if(!r.ok)throw 0;return(await r.json()).filter(e=>e.type==='file').map(e=>e.name).sort();}catch(_){return[DEFAULT_GAME];}};
  const setMoniker=()=>{const value=window.JASPER_POKEDEX_VERSION||'';document.querySelectorAll('#pokedexBetaMoniker,.desktop-sidebar-brand .beta').forEach(e=>e.textContent=value);document.title=value?`Jasper's Pokédex — ${value}`:"Jasper's Pokédex";};

  const ensureBanner=()=>{let b=document.getElementById('dexProgressBanner');if(!b){const w=document.getElementById('desktopWorkspace'),t=document.getElementById('desktopTableContainer');if(!w||!t)return null;b=document.createElement('div');b.id='dexProgressBanner';b.innerHTML='<span class="dex-progress-icon">i</span><span class="dex-progress-text"></span>';w.insertBefore(b,t);}return b;};
  const updateBanner=(pokemon=activePokemon,state=readState(activeGame))=>{const b=ensureBanner(),text=b?.querySelector('.dex-progress-text');if(!text)return;const done=pokemon.reduce((n,p)=>n+(state[p.id]===true?1:0),0),total=pokemon.length;text.textContent=`${done} of ${total} Pokémon registered · ${total-done} remaining · ${Math.round(done/Math.max(1,total)*100)}% complete`;};
  const updateBoxCounters=()=>{const state=readState(activeGame);document.querySelectorAll('#boxContainer .pc-box').forEach((box,index)=>{const items=activePokemon.slice(index*BOX_SIZE,(index+1)*BOX_SIZE),done=items.reduce((n,p)=>n+(state[p.id]===true?1:0),0),counter=box.querySelector('.box-completion-counter');if(counter)counter.textContent=`${done}/${items.length}`;});};

  const renderCell=(p,state)=>{const c=document.createElement('div');c.className=`cell${state[p.id]===true?' completed':''}`;c.dataset.id=p.id;c.dataset.num=p.num;c.dataset.name=p.name;c.innerHTML=`<span class="dex-num">${esc(p.num)}</span><span class="name">${esc(p.baseName)}${p.form?` <span class="form">${esc(p.form)}</span>`:''}</span><div class="checkbox"></div>`;return c;};
  const renderBoxes=(pokemon,state)=>{const root=document.getElementById('boxContainer');if(!root)return;root.replaceChildren();const count=Math.max(1,Math.ceil(pokemon.length/BOX_SIZE));for(let i=0;i<count;i++){const items=pokemon.slice(i*BOX_SIZE,(i+1)*BOX_SIZE),box=document.createElement('section');box.className='pc-box';const title=document.createElement('div');title.className='box-title';title.innerHTML=`<span>Box ${i+1} — ${items.length?`Dex #${items[0].num}–#${items[items.length-1].num}`:'Empty'}</span><span class="box-completion-counter">0/${items.length}</span>`;const wrap=document.createElement('div');wrap.className='grid-wrapper';const grid=document.createElement('div');grid.className='grid';grid.style.gridTemplateColumns=`repeat(${BOX_COLUMNS},minmax(110px,1fr))`;grid.style.gridTemplateRows=`repeat(${BOX_ROWS},minmax(58px,auto))`;items.forEach(p=>grid.appendChild(renderCell(p,state)));while(grid.children.length<BOX_SIZE){const e=document.createElement('div');e.className='cell empty';e.setAttribute('aria-hidden','true');grid.appendChild(e);}wrap.appendChild(grid);box.append(title,wrap);root.appendChild(box);}};
  const renderList=(pokemon,state)=>{const root=document.getElementById('listContainer');if(!root)return;root.replaceChildren();pokemon.forEach(p=>{const row=document.createElement('div');row.className=`list-row${state[p.id]===true?' completed':''}`;row.dataset.id=p.id;row.dataset.num=p.num;row.dataset.name=p.name;row.innerHTML=`<div class="checkbox"></div><div class="list-info"><span class="dex-num">#${esc(p.num)}</span><span class="name">${esc(p.baseName)}${p.form?` <span class="form">${esc(p.form)}</span>`:''}</span></div>`;root.appendChild(row);});};

  const installSearch=()=>{let input=document.getElementById('searchInput'),root=document.getElementById('searchResults');if(!input||!root)return;const fresh=input.cloneNode(true);fresh.id='searchInput';fresh.placeholder='Search...';fresh.autocomplete='off';input.replaceWith(fresh);let clear=document.getElementById('searchClearButton');if(!clear){clear=document.createElement('button');clear.id='searchClearButton';clear.type='button';clear.setAttribute('aria-label','Clear search');clear.textContent='×';document.querySelector('.search-wrapper')?.appendChild(clear);}const syncClear=()=>{clear.hidden=!fresh.value;};clear.onclick=()=>{fresh.value='';fresh.dispatchEvent(new Event('input',{bubbles:true}));fresh.focus();};fresh.addEventListener('input',()=>{syncClear();renderSearch(fresh.value);});fresh.addEventListener('focus',()=>{if(fresh.value)renderSearch(fresh.value);});syncClear();root.onclick=e=>{const row=e.target.closest('.search-result-item[data-id]');if(!row)return;const id=row.dataset.id;if(e.target.closest('.search-jump')){const target=document.querySelector(`#boxContainer [data-id="${CSS.escape(id)}"]`)||document.querySelector(`#listContainer [data-id="${CSS.escape(id)}"]`);target?.scrollIntoView({behavior:'smooth',block:'center'});if(target){target.classList.remove('jump-highlight');void target.offsetWidth;target.classList.add('jump-highlight');}root.style.display='none';return;}togglePokemon(id);};document.addEventListener('click',e=>{if(!e.target.closest('.search-wrapper'))root.style.display='none';});if(!document.getElementById('v011SearchStyles')){const s=document.createElement('style');s.id='v011SearchStyles';s.textContent=`.search-wrapper{position:relative}.search-wrapper #searchInput{padding-right:42px}.search-wrapper #searchClearButton{position:absolute;right:10px;top:50%;transform:translateY(-50%);width:24px;height:24px;border:0;border-radius:50%;background:#e2e8f0;color:#475569;font-size:18px;line-height:20px;padding:0;cursor:pointer}.search-wrapper #searchClearButton[hidden]{display:none}.jump-highlight{outline:2px solid #2563eb!important;outline-offset:2px}@media(max-width:640px){#searchInput{font-size:16px!important}.search-results{left:0;right:0;width:100%}}`;document.head.appendChild(s);}};
  const renderSearch=query=>{const root=document.getElementById('searchResults');if(!root)return;const q=normalize(String(query).trim());root.replaceChildren();if(!q){root.style.display='none';return;}const state=readState(activeGame),matches=activePokemon.filter(p=>normalize(p.name).includes(q)||p.num.includes(q)).sort((a,b)=>a.name.localeCompare(b.name));if(!matches.length){root.style.display='none';return;}matches.slice(0,50).forEach(p=>{const row=document.createElement('div');row.className=`search-result-item${state[p.id]===true?' completed':''}`;row.dataset.id=p.id;row.innerHTML=`<div class="checkbox"></div><span class="dex-num">#${esc(p.num)}</span><span class="name">${esc(p.baseName)}${p.form?` <span class="form">${esc(p.form)}</span>`:''}</span><button class="search-jump" type="button">Jump</button>`;root.appendChild(row);});root.style.display='block';};

  const installViewToggle=()=>{const b=document.getElementById('boxViewBtn'),l=document.getElementById('listViewBtn'),boxes=document.getElementById('boxContainer'),list=document.getElementById('listContainer');if(!b||!l||!boxes||!list)return;const box=()=>{boxes.style.display='flex';list.style.display='none';b.classList.add('active');l.classList.remove('active');};const listView=()=>{boxes.style.display='none';list.style.display='block';l.classList.add('active');b.classList.remove('active');};b.onclick=box;l.onclick=listView;box();};
  const updateVisuals=(id,done)=>document.querySelectorAll(`[data-id="${CSS.escape(id)}"]`).forEach(e=>e.classList.toggle('completed',done));
  const togglePokemon=id=>{const state=readState(activeGame);state[id]=state[id]!==true;writeState(activeGame,state);updateVisuals(id,state[id]);updateBanner(activePokemon,state);updateBoxCounters();renderSearch(document.getElementById('searchInput')?.value||'');};
  const bindSelection=()=>{const box=document.getElementById('boxContainer'),list=document.getElementById('listContainer');if(box)box.onclick=e=>{const t=e.target.closest('.cell[data-id]');if(t&&!t.classList.contains('empty'))togglePokemon(t.dataset.id);};if(list)list.onclick=e=>{const t=e.target.closest('.list-row[data-id]');if(t)togglePokemon(t.dataset.id);};};

  const renderGame=async game=>{const pokemon=await loadGame(game);activeGame=game;activePokemon=pokemon;window.JASPER_ACTIVE_GAME=game;window.JASPER_POKEDEX={game,pokemon,boxSize:BOX_SIZE,boxColumns:BOX_COLUMNS,boxRows:BOX_ROWS};const state=readState(game);renderBoxes(pokemon,state);renderList(pokemon,state);installViewToggle();installSearch();bindSelection();updateBanner(pokemon,state);updateBoxCounters();setMoniker();};
  const renderTabs=games=>{const root=document.querySelector('.tabs-container');if(!root)return;root.replaceChildren();games.forEach(game=>{const b=document.createElement('button');b.type='button';b.className='tab-btn';b.dataset.game=game;b.textContent=game==='White2'?'Pokémon White 2':game.replace(/([a-z])([A-Z])/g,'$1 $2');root.appendChild(b);});root.onclick=e=>{const b=e.target.closest('.tab-btn[data-game]');if(b)renderGame(b.dataset.game).catch(console.error);};};
  const boot=async()=>{if(booted)return;booted=true;let tries=0;while(!window.JASPER_POKEDEX_VERSION&&tries++<100)await new Promise(r=>setTimeout(r,10));setMoniker();const games=await discoverGames();renderTabs(games);await renderGame(games.includes(DEFAULT_GAME)?DEFAULT_GAME:games[0]);};
  window.addEventListener('jasper:pokedex-state-synced',e=>renderGame(e.detail?.game||activeGame).catch(console.error));
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
