(() => {
  'use strict';
  const API_ROOT='https://pokeapi.co/api/v2';
  const cache=new Map(),pending=new Map();
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const title=v=>String(v||'').split('-').map(x=>x?x[0].toUpperCase()+x.slice(1):x).join(' ');
  const get=async path=>{const url=`${API_ROOT}/${path.replace(/^\//,'')}`;if(cache.has(url))return cache.get(url);if(pending.has(url))return pending.get(url);const p=fetch(url,{headers:{Accept:'application/json'}}).then(async r=>{if(!r.ok)throw Error(`PokéAPI request failed (${r.status})`);const d=await r.json();cache.set(url,d);pending.delete(url);return d;}).catch(e=>{pending.delete(url);throw e;});pending.set(url,p);return p;};
  const slug=card=>String(card?.dataset?.name||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[()]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  const styles=()=>{if(document.getElementById('jasperPokedexApiUiStyles'))return;const s=document.createElement('style');s.id='jasperPokedexApiUiStyles';s.textContent=`#desktopRightSidebar .jasper-api-pokedex{display:flex;flex-direction:column;gap:16px;min-height:0;height:100%;overflow:auto}#desktopRightSidebar .jasper-api-pokedex-title{margin:0;font-size:22px;line-height:1.2;font-weight:700;color:inherit}#desktopRightSidebar .jasper-api-pokedex-subtitle{margin:-10px 0 0;font-size:12px;opacity:.65}#desktopRightSidebar .jasper-api-card{border:1px solid rgba(100,116,139,.28);border-radius:8px;padding:12px;background:rgba(148,163,184,.06)}#desktopRightSidebar .jasper-api-card h2{margin:0 0 10px;font-size:14px;line-height:1.2;font-weight:700}#desktopRightSidebar .jasper-api-row{display:flex;justify-content:space-between;gap:12px;padding:5px 0;font-size:13px}#desktopRightSidebar .jasper-api-row+.jasper-api-row{border-top:1px solid rgba(100,116,139,.16)}#desktopRightSidebar .jasper-api-label{opacity:.7}#desktopRightSidebar .jasper-api-value{text-align:right;font-weight:600}`;document.head.appendChild(s)};
  const loading=card=>{const side=document.getElementById('desktopRightSidebar');if(!side)return;styles();side.innerHTML=`<div class="jasper-api-pokedex"><p class="jasper-api-pokedex-title">Pokédex</p><p class="jasper-api-pokedex-subtitle">Loading Pokémon data…</p><section class="jasper-api-card"><h2>Pokémon</h2><div class="jasper-api-row"><span class="jasper-api-label">Selected</span><span class="jasper-api-value">${esc(card?.dataset?.name||'Unknown')}</span></div></section></div>`};
  const render=(card,data)=>{const side=document.getElementById('desktopRightSidebar');if(!side)return;styles();const name=title(data.name),regional=card?.dataset?.num||'—',national=String(data.id).padStart(3,'0'),types=(data.types||[]).sort((a,b)=>a.slot-b.slot).map(x=>title(x.type?.name)).join(' / ')||'—';side.innerHTML=`<div class="jasper-api-pokedex"><p class="jasper-api-pokedex-title">${esc(name)}</p><p class="jasper-api-pokedex-subtitle">Pokédex information</p><section class="jasper-api-card"><h2>Pokémon</h2><div class="jasper-api-row"><span class="jasper-api-label">Pokémon</span><span class="jasper-api-value">${esc(name)}</span></div><div class="jasper-api-row"><span class="jasper-api-label">Regional Dex Number</span><span class="jasper-api-value">#${esc(regional)}</span></div><div class="jasper-api-row"><span class="jasper-api-label">National Dex Number</span><span class="jasper-api-value">#${esc(national)}</span></div><div class="jasper-api-row"><span class="jasper-api-label">Type</span><span class="jasper-api-value">${esc(types)}</span></div></section><section class="jasper-api-card"><h2>Evolutionary Chain</h2><div class="jasper-api-row"><span class="jasper-api-label">Status</span><span class="jasper-api-value">Loading…</span></div></section><section class="jasper-api-card"><h2>Wild Locations</h2><div class="jasper-api-row"><span class="jasper-api-label">Status</span><span class="jasper-api-value">Loading…</span></div></section><section class="jasper-api-card"><h2>Additional Information</h2><div class="jasper-api-row"><span class="jasper-api-label">Status</span><span class="jasper-api-value">Loading…</span></div></section></div>`};
  const error=e=>{const side=document.getElementById('desktopRightSidebar');if(side)side.innerHTML='<div class="jasper-api-pokedex"><p class="jasper-api-pokedex-title">Pokédex</p><section class="jasper-api-card"><h2>Unable to load data</h2><p class="jasper-api-error">PokéAPI could not be reached. The rest of the Pokédex remains available.</p></section></div>';console.error('[Jasper PokéAPI]',e)};
  const open=async card=>{if(!card)return;loading(card);try{const name=slug(card);if(!name)throw Error('Selected Pokémon has no API name.');render(card,await get(`pokemon/${name}`))}catch(e){error(e)}};
  window.JASPER_POKEDEX_UI={open};
})();
